//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProjectFenix.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_a78cef_finixier : DbContext
    {
        public db_a78cef_finixier()
            : base("name=db_a78cef_finixier")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adelanto> Adelantoes { get; set; }
        public virtual DbSet<Aguinaldo> Aguinaldoes { get; set; }
        public virtual DbSet<Ausencia> Ausencias { get; set; }
        public virtual DbSet<Cesantia> Cesantias { get; set; }
        public virtual DbSet<Colaborador> Colaboradors { get; set; }
        public virtual DbSet<Correo> Correos { get; set; }
        public virtual DbSet<Departamento> Departamentoes { get; set; }
        public virtual DbSet<DetalleMarca> DetalleMarcas { get; set; }
        public virtual DbSet<DetallePlanilla> DetallePlanillas { get; set; }
        public virtual DbSet<Embargo> Embargos { get; set; }
        public virtual DbSet<EstadoCivil> EstadoCivils { get; set; }
        public virtual DbSet<EstadoPlanilla> EstadoPlanillas { get; set; }
        public virtual DbSet<Feriado> Feriadoes { get; set; }
        public virtual DbSet<Genero> Generoes { get; set; }
        public virtual DbSet<HorasExtra> HorasExtras { get; set; }
        public virtual DbSet<ImpuestoRenta> ImpuestoRentas { get; set; }
        public virtual DbSet<Incapacidad> Incapacidads { get; set; }
        public virtual DbSet<Jornada> Jornadas { get; set; }
        public virtual DbSet<LlegadaTardia> LlegadaTardias { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<Permiso> Permisos { get; set; }
        public virtual DbSet<Planilla> Planillas { get; set; }
        public virtual DbSet<Preaviso> Preavisoes { get; set; }
        public virtual DbSet<Puesto> Puestoes { get; set; }
        public virtual DbSet<RangoImpuesto> RangoImpuestoes { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<Rubro> Rubroes { get; set; }
        public virtual DbSet<RubrosDeduccion> RubrosDeduccions { get; set; }
        public virtual DbSet<Salario> Salarios { get; set; }
        public virtual DbSet<Telefono> Telefonoes { get; set; }
        public virtual DbSet<TipoCorreo> TipoCorreos { get; set; }
        public virtual DbSet<TipoHoraExtra> TipoHoraExtras { get; set; }
        public virtual DbSet<TipoPagoFeriado> TipoPagoFeriadoes { get; set; }
        public virtual DbSet<TipoTelefono> TipoTelefonoes { get; set; }
        public virtual DbSet<Turno> Turnoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Vacacione> Vacaciones { get; set; }
    }
}
