//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProjectFenix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleMarca
    {
        public int idDetMarca { get; set; }
        public int Cedula { get; set; }
        public string UsuarioReg { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public int CantHoras { get; set; }
        public int IdMarca { get; set; }
        public int idRubro { get; set; }
        public bool Estado { get; set; }
    
        public virtual Colaborador Colaborador { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Rubro Rubro { get; set; }
    }
}
