//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProjectFenix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marca()
        {
            this.DetalleMarcas = new HashSet<DetalleMarca>();
        }
    
        public int IdMarca { get; set; }
        public int Cedula { get; set; }
        public int NumMarca { get; set; }
        public int Machn { get; set; }
        public int Codhuella { get; set; }
        public string Nombre { get; set; }
        public int Mode { get; set; }
        public int IOMd { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Colaborador Colaborador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleMarca> DetalleMarcas { get; set; }
    }
}
